export const CLOCK_CONSTANTS = {
    CENTER_OFFSET: 50,
    RADIUS : 45,
    DEGREES_PER_HOUR: 30,
    DEG_TO_RAD: Math.PI / 180,

    //hand
    DEGREE_PER_MINUTE_SECOND: 6,
    MINUTE_ADJUSTMENT: 0.5,
    SECOND_ADJUSTMENT: 0.1,
    OFFSET_ROTATION: 180
} 